name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Check Out
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
      - run: yarn
      - run: yarn test
